DOMAIN = "foli"
GTFSREST = "http://data.foli.fi/gtfs"
SMREST = "http://data.foli.fi/siri/sm"
VMREST = "http://data.foli.fi/siri/vm"
ALERTSREST = "http://data.foli.fi/alerts"
CITYBOKEREST = "http://data.foli.fi/citybike"
ATTRIBUTION = "Turku region public transport's transit and timetable data. The administrator of data is Turku region public transport. Dataset is downloaded from http://data.foli.fi/ using the license Creative Commons Attribution 4.0 International (CC BY 4.0)."
